kind: pipeline
type: kubernetes
#type: docker
name: first

concurrency:
  limit: 1

steps:
  - name: skip
    image: wuzhixiang/awscli
    commands:
      - exit 78
  - name: should-not-run
    image: wuzhixiang/awscli
    commands:
      - ls

trigger:
  branch:
  - master
  event:
  - custom
  - push
  - pull_request

---
kind: pipeline
type: kubernetes
#type: docker
name: dev

depends_on:
- first

steps:
  - name: test
    image: wuzhixiang/awscli
    commands:
      - ls

trigger:
  branch:
  - master
  event:
  - custom
  - push
  - pull_request